version: "3.5" #check version

services:

  nginx:
    depends_on:
      - wordpress
    # build: ./requirements/nginx --name nginx
    image: nginx:latest #for testing
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
      - "8080:8080"
    # environment:
    #   - NGINX_PORT=443
    volumes:
      - wordpress_files:/var/www/html
      - nginx_config:/etc/nginx/conf.d
    networks:
      - inception

  wordpress:
    image: wordpress:php8.3-fpm #for testing
    # build: ./requirements/wordpress --name wordpress
    container_name: wordpress
    restart: unless-stopped 
    env_file: 
      - .env
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_HOST=mariadb:3306

    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
  
  mariadb:
    image: mariadb:latest #for testing
    # build: ./requirements/mariabd --name mariadb
    container_name: mariadb
    restart: unless-stopped # or allways
    env_file:
      - .env
    environment:
      -  MYSQL_DATABASE=wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

volumes:
  wordpress_files:
  # remove driver and driver_opts for production?
    driver: local
    driver_opts:
      device: ./requirements/wordpress/files
      o: bind
      type: none

  db_data:  
  # remove driver and driver_opts for production?
    driver: local
    driver_opts:
      device: ./requirements/mariadb/data
      o: bind
      type: none

  nginx_config:
    driver: local
    driver_opts:
      device: ./requirements/nginx/conf

      o: bind
      type: none

networks:
  inception:
    driver: bridge
    
# consider using secrets for passwords: https://docs.docker.com/compose/use-secrets/