services:

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/wordpress
      - nginx_config:/etc/nginx/conf.d
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    restart: unless-stopped 
    env_file: 
      - .env
    volumes:
      - wordpress_files:/var/www/wordpress
    networks:
      - inception
  
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: unless-stopped # or allways
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception

# TODO: remove driver and driver_opts for evaluation?
volumes:
  wordpress_files:
    driver: local
    driver_opts:
      device: ./requirements/wordpress/files
      o: bind
      type: none

  db_data:  
    driver: local
    driver_opts:
      device: ./requirements/mariadb/data
      o: bind
      type: none

  nginx_config:
    driver: local
    driver_opts:
      device: ./requirements/nginx/conf
      o: bind
      type: none

networks:
  inception:
    driver: bridge